// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY7VkX8a-RRwubXx8nPg3U6qZrO2A0a4g',
    appId: '1:1041119329808:android:513893be295e944f2a5495',
    messagingSenderId: '1041119329808',
    projectId: 'wh1doulike',
    databaseURL: 'https://wh1doulike-default-rtdb.firebaseio.com',
    storageBucket: 'wh1doulike.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUO9Bcc7rT7QXizUAqhDnEHVIbKNN_mfA',
    appId: '1:1041119329808:ios:3788dac7a264d3fe2a5495',
    messagingSenderId: '1041119329808',
    projectId: 'wh1doulike',
    databaseURL: 'https://wh1doulike-default-rtdb.firebaseio.com',
    storageBucket: 'wh1doulike.appspot.com',
    androidClientId: '1041119329808-2rlre0ufe74q890aol9qjhlqrpqtitgj.apps.googleusercontent.com',
    iosClientId: '1041119329808-tbqapr9qnri5mifv63qdb5scue81kqk1.apps.googleusercontent.com',
    iosBundleId: 'com.tmksolutions.wh1dulike.wh1dulike',
  );
}
